// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5qVAbC-weHIAStQ2ZQwYKiHN9fCTOUho',
    appId: '1:845834716358:web:30dd28646e120d6f3583c7',
    messagingSenderId: '845834716358',
    projectId: 'steppe-compas',
    authDomain: 'steppe-compas.firebaseapp.com',
    storageBucket: 'steppe-compas.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfAMgOxmEBtq7XIoHBXu1CQMj-hlOcDBI',
    appId: '1:845834716358:android:05625f6844869a933583c7',
    messagingSenderId: '845834716358',
    projectId: 'steppe-compas',
    storageBucket: 'steppe-compas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvxLuelLWqMI7uVafIeQjl3EEoB2uyhrQ',
    appId: '1:845834716358:ios:19f42f0b077b340f3583c7',
    messagingSenderId: '845834716358',
    projectId: 'steppe-compas',
    storageBucket: 'steppe-compas.firebasestorage.app',
    iosBundleId: 'com.example.kazakhstanTravel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvxLuelLWqMI7uVafIeQjl3EEoB2uyhrQ',
    appId: '1:845834716358:ios:19f42f0b077b340f3583c7',
    messagingSenderId: '845834716358',
    projectId: 'steppe-compas',
    storageBucket: 'steppe-compas.firebasestorage.app',
    iosBundleId: 'com.example.kazakhstanTravel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5qVAbC-weHIAStQ2ZQwYKiHN9fCTOUho',
    appId: '1:845834716358:web:921616bdaff4cd583583c7',
    messagingSenderId: '845834716358',
    projectId: 'steppe-compas',
    authDomain: 'steppe-compas.firebaseapp.com',
    storageBucket: 'steppe-compas.firebasestorage.app',
  );

}